name: Lint and Test the Codex Local Harness

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Get Codex
      run: |
        curl -s https://get.codex.storage/install.sh | bash

    - name: Lint
      uses: ludeeus/action-shellcheck@master
      with:
        ignore_paths: >-
          test/bats
          test/test_helper

    - name: Run Tests
      run: ./test/bats/bin/bats test/
